### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by webzi** [Decicus/twitch-log-bot#6]
Are there any easy way to search for a specific word in messages?

Would be nice to have in the interface imo.

But I guess the only way right now, is with some sort of query in the Google datastore?

**Comment by Decicus** [comment]
It's not possible with Datastore, due to the way it works (you can't search for a partial match).

I actually regret using Datastore for this, as it's not really the best choice for this type of project.

The closest thing you can do is run a GQL query via the UI: `SELECT * FROM `twitch-log-bot` WHERE message CONTAINS 'test'` - but this will only match messages exactly and doesn't "search" for the text.
